export enum URL {
  EMPTY = '',
  HOME = '/',
  HOME_CSS = '/home/css/index.css',
  HOME_JS = '/home/js/index.js',
  DASHBOARD = '/main/dashboard',
  DASHBOARD_CSS = '/css/index.css',
  DASHBOARD_JS = '/css/index.js',
  REDIRECT_CODE = '/:code',
  SHORT_URL = '/api/v1/short-url',
  SHORT_URL_GET_ALL = '/get-all',
  SHORT_URL_CREATE = '/create',
  SHORT_URL_UPDATE = '/update',
  SHORT_URL_DELETE = '/delete',
  NOT_FOUND = '*',
  NOT_FOUND_CSS = '/not-found/css/index.css',
  NOT_FOUND_JS = '/not-found/js/index.js',
}
